# Generated by Django 2.0.6 on 2019-05-11 16:47

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vkapi',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
