# Generated by Django 2.0.6 on 2019-05-12 17:00

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_vkapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='css',
            field=picklefield.fields.PickledObjectField(editable=False, null=20000),
        ),
        migrations.AddField(
            model_name='profile',
            name='html',
            field=picklefield.fields.PickledObjectField(editable=False, null=20000),
        ),
    ]
