# Generated by Django 2.0.6 on 2019-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190512_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='css',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='html',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
