# Generated by Django 2.0.6 on 2019-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190512_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.AlterField(
            model_name='profile',
            name='vklogin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vkpassword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtubetoken',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
