# Generated by Django 2.0.6 on 2019-05-13 18:37

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190513_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formParser',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
