# Generated by Django 2.0.6 on 2019-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_formparser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vktoken',
            field=models.CharField(default='', max_length=100),
        ),
    ]
