# Generated by Django 2.0.6 on 2019-08-23 20:15

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_vktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_object', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('token', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('source', models.CharField(default='', max_length=3)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(default='')),
                ('html', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_api_object',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='apis',
            field=models.ManyToManyField(to='users.API'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pages',
            field=models.ManyToManyField(to='users.Page'),
        ),
    ]
