# Generated by Django 2.0.6 on 2019-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190823_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
