# Generated by Django 2.0.6 on 2019-05-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
